[package]
name = "nlpo"
version = "1.0.0"
description = "c++ program option and command library"

[cmake]
version  = "3.10"
option   = ""
builder  = "ninja"
compiler = "clang++"

[compiler] 
clang++ = {option = "-std=c++17 -Wall -g -fPIC -O0", version = "7.0", ccache=true}
g++     = {option = "-std=c++17 -Wall -g -fPIC -O0", version = "8.0", ccache=true}

[builder]
ninja   = {option = "-j4"}
make    = {option = "-j4"}

[[lib]]
name   = "nlpo"
source = ["include/.*" ,"src/.*"]

[dependencies]
Boost   = {cmake = " ${Boost_LIBRARIES}", components="system filesystem"}