[package]
name = "nlpo"
version = "1.0.3"
description = "c++ program option and command library"
git = "https://github.com/injae/nlpo.git"

[lib]
name   = "nlpo"
namespace = "nlpo"
type   = "shared"
source = ["src/.*"]

[dependencies]
fmt = "6.0.0"

    