[package]
name = "nlpo"
version = "1.0.1"
description = "c++ program option and command library"
git = "https://github.com/injae/nlpo.git"

[[lib]]
name   = "nlpo"
type   = "static"
source = ["src/.*"]

[[bin]]
name = "test"
source = ["src/main.cpp"]

[dependencies]
fmt = "6.0.0"

    