[package]
name = "nlpo"
version = "1.0.0"
description = "c++ program option and command library"

[compiler] 
clang = {option = "-std=c++17 -Wall -g -fPIC -O0"}
gcc   = {option = "-std=c++17 -Wall -g -fPIC -O0"}
msvc  = {option = "/std:c++17"}
xcode = {option = "-std=c++1y -Wall -g -fPIC -O0"}

[[lib]]
name   = "nlpo"
type   = "static"
source = ["src/.*"]

[dependencies]
fmt={module="fmt::fmt", version="lastest"}