[package]
name = "nlpo"
version = "0.0.3"
description = "c++ program option and command library"
git = "https://github.com/injae/nlpo.git"

[lib]
name   = "nlpo"
namespace = "nlpo"
type   = "static"
source = ["src/.*"]

[dependencies]
fmt = {version="8.0.1", link="private"}

    